### PR TITLE
Replaced the storage container for HDU from vector to deque to prevent reference invalidation in fits_reader

### LINKED ISSUE #162: References get invalidated on insertion of a new HDU by the user
Adding a new HDU to the list of HDU's by the user results in invalidating the old references held by the user.

Example :
```
auto& astro_data= fits::open("sample.fits");
auto& ascii_hdu = fits::convert_to<ascii_hdu>(astro_data["TABLE"]);

auto& new_bin_hdu = // Creates a new binary table and stores data in it

astro_data.add(new_bin_hdu); 

// After this any operation to ascii_hdu is invalid as the reference has got invalidated

```
This is happening because in fits_reader.hpp the HDUs are stored inside a vector. If the preallocated buffer is filled up then the vector will expand the size and this expansion involves creating a new buffer copying all the elements. Thus the references created before point to old garbage memory causing the crash.

This problem can be removed by using non contiguous container ( std::list or std::deque )

After looking at the benchmarks here  : (https://baptiste-wicht.com/posts/2012/12/cpp-benchmark-vector-list-deque.html)[https://baptiste-wicht.com/posts/2012/12/cpp-benchmark-vector-list-deque.html]

The best candidate would be std::deque. Also references never get invalidated in std::deque and std::deque sometimes performs much better than std::vector

### PR DESCRIPTION
**Pull request by gopi487krishna**
### Description 
Fixed the problem of reference invalidation in fits_reader

### References
#162

### CODE REVIEW

**Review by lpranam — APPROVED** [review]
Looks good

File: include/boost/astronomy/io/fits_reader.hpp [hunk 1]
```diff
@@ -148,28 +147,28 @@ namespace boost { namespace astronomy { namespace io {
...
-        typename ExtensionsSupported::Extension& operator [](int index) {
+        typename ExtensionsSupported::Extension& operator [](int index)  {
             return hdu_list.at(index);
         }
 
         /**
          * @brief Returns the HDU based on the hdu_name 
         */
-        typename ExtensionsSupported::Extension& operator [](const std::string& hdu_name) {
+        typename ExtensionsSupported::Extension& operator [](const std::string& hdu_name)  {
```
Comment (lpranam) [inline include/boost/astronomy/io/fits_reader.hpp]: nitpicking: remove extra space between ) and {

File: include/boost/astronomy/io/fits_reader.hpp [hunk 2]
```diff
@@ -148,28 +147,28 @@ namespace boost { namespace astronomy { namespace io {
         /**
          * @brief Returns the HDU at given index
         */
-        typename ExtensionsSupported::Extension& operator [](int index) {
+        typename ExtensionsSupported::Extension& operator [](int index)  {
```
Comment (lpranam) [inline include/boost/astronomy/io/fits_reader.hpp]: nitpicking: remove extra space between ) and {

**Review by lpranam — CHANGES_REQUESTED** [review]
please change commit message to something more descriptive...
