### PR TITLE
bug fix of cross function in arithmetic.hpp

### LINKED ISSUE #79: Wrong units generated with Cross product
When `cartesian_representation` is crossed with other types of representation wrong units are generated due to resultant units are generated from original units in the return statement.

### PR DESCRIPTION
**Pull request by rjnrohit**
### Description
1. Previously, cross generate errors for some coordinate system i.e previous version can't able to identify bu::conversion_factor(plane_angle, meter for cross_product(cartesian point, spherical point) ) in calculation part of code.
2. Now cross returns cross product in requested representation( It returns correct units for every representation).
3. Updated tests for cross product.

### References
Fixes #79 

### Tasklist

- [x] Add test case(s)
- [x] Ensure all CI builds pass
- [x] Review and approve

### CODE REVIEW

**Comment by rjnrohit** [comment]
@lpranam @sarthak2007  I made a separate PR for cross product. you may wanna review it.

File: include/boost/astronomy/coordinate/arithmetic.hpp [hunk 1]
```diff
@@ -72,54 +72,161 @@ auto cross
         bg::cs::cartesian
     > tempPoint1, tempPoint2, result;
 
+    auto cartesian1 = make_cartesian_representation(representation1);
```
Comment (sarthak2007) [inline include/boost/astronomy/coordinate/arithmetic.hpp]: There is no need to convert `representation1` to cartesian as it is already in cartesian.

**Review by sarthak2007 — CHANGES_REQUESTED** [review]

**Review by sarthak2007 — APPROVED** [review]

**Review by lpranam — APPROVED** [review]
